;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        adelrune/avy-goto-char-timer-flash
        adelrune/backward-kill-symbol
        adelrune/backward-kill-word
        adelrune/backward-symbol
        adelrune/backward-word
        adelrune/begin-line
        adelrune/expand-dong
        adelrune/forward-kill-symbol
        adelrune/forward-kill-word
        adelrune/forward-paragraph
        adelrune/forward-symbol
        adelrune/forward-word
        adelrune/good-comment
        adelrune/recenter-top-bottom
        adelrune/ruthlessly-kill-lines
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        cua-copy-region
        cua-copy-region
        cua-copy-region
        cua-copy-region
        cua-copy-region
        cua-cut-region
        cua-paste
        downcase-region
        forward-sexp
        helm-show-kill-ring
        ignore
        json-increment-number-at-point
        markdown-enter-key
        markdown-outdent-or-delete
        mouse-set-region
        smart-tab
        ))

(setq mc/cmds-to-run-once
      '(
        adelrune/helm-M-x
        adelrune/mc-mark-next-symbol
        adelrune/save
        centaur-tabs-forward
        cua--prefix-override-handler
        cua--prefix-override-handler
        cua--prefix-override-handler
        cua--prefix-override-handler
        cua--prefix-override-handler
        custom/copy-across-cursors
        helm-buffers-list
        helm-confirm-and-exit-minibuffer
        multiple-cursors-mode
        tabbar-backward-tab
        tabbar-forward-tab
        ))
